version: '3.8'

services:
  ctfserver:
    image: dhrsoulslayer/ctfserver
    ports:
      - "8990:8990"
    volumes:
      - ./ctf_database.db:/usr/src/app/ctf_database.db
    environment:
      - NODE_ENV=production
