version: '3.8'

services:
  ctfserver:
    image: ctfserver:latest
    network_mode: host
    volumes:
      - ./ctf_database.db:/usr/src/app/ctf_database.db
    environment:
      - NODE_ENV=production
